# SWE-bench Evaluation Scenario
#
# Green Agent: Pulls tasks from SWE-bench Verified, validates patches in Docker
# Purple Agent: Solves coding tasks using LLM
#
# Usage: uv run python src/run_scenario.py scenarios/swebench/scenario.toml
#        uv run python src/run_scenario.py scenarios/swebench/scenario.toml --serve-only

[green]
url = "http://localhost:9009"
command = "uv run python src/server.py --host 127.0.0.1 --port 9009"
cwd = "../.."  # green-agent root

[participants.solver]
url = "http://localhost:9010"
command = "uv run python src/server.py --host 127.0.0.1 --port 9010"
cwd = "/Users/soumyabatra/Documents/purple-swebench"

[config]
# Evaluation configuration passed to the green agent
#max_tasks = 1
#repo = "astropy/astropy"
repo = "sympy/sympy"
difficulty = "<15 min fix"
max_tasks = 10
# instance_id = "pylint-dev__pylint-4661" #"sympy__sympy-20916" #"pylint-dev__pylint-4661" 
# max_turns = 10                           # default = 10
# max_attempts = 3                         # specify max k for pass@k, default k = 1
# Optional filters:
# repo = "django/django"                 # Filter by repo
# difficulty = "<15 min fix"                    # Filter by difficulty
